### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by joydeepmedhi** [hikvision-research/SSOD#11]
`Traceback (most recent call last):
  File "examples/train/train.py", line 193, in <module>
    main()
  File "examples/train/train.py", line 182, in main
    train_detector(
  File "/app/jomedhi/SSOD-main/mmdet_extension/apis/train.py", line 164, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/app/jomedhi/SSOD-main/mmdet_extension/core/hooks/semi_eval_hooks.py", line 51, in after_train_epoch
    if not self.by_epoch or not self.evaluation_flag(runner):
AttributeError: 'SemiEvalHook' object has no attribute 'evaluation_flag'`

Error during validation between training

**Comment by wang-TJ-20** [comment]
@joydeepmedhi hello, Have you solved this problem

**Comment by wang-TJ-20** [comment]
@joydeepmedhi  maybe you need to use mmdet=2.10.0
